/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/data/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/state/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed": "#1b1c1c",
        surface: "#f9f9f9",
        "secondary-fixed-dim": "#adabaa",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "surface-bright": "#f9f9f9",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#474747",
        "on-secondary-container": "#1b1c1c",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#3c3b3b",
        "surface-variant": "#e2e2e2",
        "primary-fixed": "#5e5e5e",
        "surface-container-low": "#f3f3f4",
        "on-primary-fixed": "#ffffff",
        "inverse-surface": "#2f3131",
        background: "#f9f9f9",
        "on-tertiary-fixed-variant": "#e4e2e2",
        outline: "#777777",
        "on-error": "#ffffff",
        "on-tertiary": "#e4e2e2",
        "on-primary": "#e2e2e2",
        "on-error-container": "#410002",
        "on-tertiary-container": "#ffffff",
        "on-surface": "#1a1c1c",
        secondary: "#5f5e5e",
        "outline-variant": "#c6c6c6",
        "surface-dim": "#dadada",
        "primary-container": "#3b3b3b",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ffffff",
        "tertiary-container": "#757474",
        tertiary: "#3b3b3b",
        "on-tertiary-fixed": "#ffffff",
        "tertiary-fixed": "#5e5e5e",
        "surface-tint": "#5e5e5e",
        "tertiary-fixed-dim": "#464747",
        "on-surface-variant": "#474747",
        "surface-container": "#eeeeee",
        "on-primary-fixed-variant": "#e2e2e2",
        "inverse-primary": "#c6c6c6",
        error: "#ba1a1a",
        "secondary-fixed": "#c8c6c5",
        "secondary-container": "#d6d4d3",
        primary: "#000000",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(26, 28, 28, 0.06)",
      },
    },
  },
  plugins: [],
}

